######################################################################
# Automatically generated by qmake (2.01a) Thu May 23 16:33:10 2013
######################################################################
QMAKE_CXXFLAGS += -std=c++0x
QT += core gui widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += baseboggleplayer.h boggleboard.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += boggleboard.cpp main.cpp mainwindow.cpp


